# EFA Backend Configuration
# Enhanced Function Agent Backend Configuration File

# Server Configuration
server:
  host: "localhost"
  port: 8000
  cors_enabled: true
  websocket_enabled: true
  max_connections: 100
  request_timeout: 30  # seconds

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: true
  log_file: "logs/efa_backend.log"
  max_log_size: 10485760  # 10MB
  backup_count: 5

# LLM Configuration
llm:
  provider: "openrouter"  # Only OpenRouter supported
  
  # OpenRouter Configuration
  openrouter:
    # Model selection - see https://openrouter.ai/models for available models
    model: "meta-llama/llama-3.1-8b-instruct:free"  # Default model (free tier)
    temperature: 0.7
    max_tokens: 2048
    top_p: 1.0
    frequency_penalty: 0.0
    presence_penalty: 0.0
    
    # OpenRouter-specific settings
    site_url: "https://github.com/yourusername/efa"  # Your app URL for attribution
    app_name: "EFA Backend"  # Your app name
    
    # Provider routing (optional)
    # provider:  # Specify preferred provider (e.g., "openai", "anthropic")
    # route: "fallback"  # Routing strategy: "fallback" for automatic fallback
    
    # Alternative models for different use cases (all using free tier)
    models:
      fast: "meta-llama/llama-3.1-8b-instruct:free"     # Fast, free model
      smart: "meta-llama/llama-3.1-70b-instruct:free"   # Higher quality free model
      creative: "meta-llama/llama-3.1-8b-instruct:free" # Creative tasks
      coding: "meta-llama/llama-3.1-8b-instruct:free"   # Code generation
      free: "meta-llama/llama-3.1-8b-instruct:free"     # Free model for testing

# MCP Server Configuration
mcp_servers:
  performance_monitoring:
    enabled: true
    max_history_size: 10000
    metrics_window_minutes: 60
    log_interval_seconds: 300
    
  http_adapter:
    timeout: 30
    max_retries: 3
    retry_delay: 1  # seconds
    
  local_server:
    auto_register_tools: true
    max_tools: 1000

# Environment Configuration
environments:
  # Environment Manager Settings
  manager:
    auto_initialize: false
    health_check_interval: 300  # seconds
    
  # Nextcloud Environment
  nextcloud:
    enabled: true
    timeout: 30
    verify_ssl: true
    
  # Custom Environment
  custom:
    enabled: true
    debug_mode: false
    timeout: 30

# Core Tools Configuration
core_tools:
  # Memory Tool
  memory:
    max_memories: 10000
    persistence_enabled: true
    persistence_path: "data/memories.json"
    consolidation_enabled: true
    similarity_threshold: 0.8
    
  # Judgment Tool
  judgment:
    default_criteria: ["accuracy", "relevance", "completeness", "clarity"]
    confidence_threshold: 0.6
    history_limit: 1000
    
  # Learning Tool
  learning:
    max_events: 1000
    pattern_threshold: 3
    performance_metrics_window: 100
    auto_pattern_detection: true
    
  # Planning Tool
  planning:
    max_plans: 100
    max_tasks_per_plan: 1000
    auto_status_updates: true
    default_max_retries: 3
    
  # Perception Tool
  perception:
    max_history: 1000
    supported_formats:
      image: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp"]
      audio: [".mp3", ".wav", ".flac", ".ogg", ".m4a"]
      video: [".mp4", ".avi", ".mov", ".wmv", ".flv"]
      document: [".pdf", ".doc", ".docx", ".txt", ".rtf"]

# Security Configuration
security:
  authentication:
    enabled: false  # Set to true in production
    method: "api_key"  # api_key, jwt, oauth
    
  rate_limiting:
    enabled: true
    default_limit: 60  # requests per minute
    burst_limit: 10
    
  cors:
    allowed_origins: ["*"]  # Restrict in production
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    
  input_validation:
    max_payload_size: 10485760  # 10MB
    sanitize_inputs: true

# Database Configuration (for future use)
database:
  type: "sqlite"  # sqlite, postgresql, mysql
  path: "data/efa.db"  # for sqlite
  # host: "localhost"  # for other databases
  # port: 5432
  # name: "efa_db"
  # pool_size: 10

# Cache Configuration
cache:
  enabled: true
  type: "memory"  # memory, redis
  max_size: 1000
  ttl: 3600  # seconds
  
# Performance Configuration
performance:
  max_workers: 4
  async_timeout: 30
  memory_limit: 1073741824  # 1GB
  
# Development Configuration
development:
  debug: false
  reload: false
  profiling: false
  mock_external_services: false

# Production Configuration
production:
  use_https: true
  ssl_cert_path: null
  ssl_key_path: null
  behind_proxy: false
  trusted_proxies: []
  
# Monitoring and Metrics
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"
  status_endpoint: "/status"
  
# Data Directories
data:
  base_dir: "data"
  logs_dir: "logs" 
  cache_dir: "cache"
  temp_dir: "temp"
  backup_dir: "backups"

# Feature Flags
features:
  websocket_support: true
  batch_requests: true
  streaming_responses: true
  file_uploads: true
  background_tasks: true
  scheduled_tasks: false
